t_MOption executing
Option test-string1 [DEFAULT](string): value = DEFAULT
Option test-string2(string): value = Hello, World
Option test-option1 [10](integer): value = 3
Option test-option2(integer): This is a test option
Please enter an INTEGER value for test-option2: This is a test option
Please enter an INTEGER value for test-option2: value = 4
Option test-option3 [10](integer: [2,20]): Invalid response: 1 (type '?' for help)
Please enter an INTEGER value between 2 and 20 for test-option3 (Default is 10): Invalid response: 21 (type '?' for help)
Please enter an INTEGER value between 2 and 20 for test-option3 (Default is 10): value = 10
Option test-option4(integer: [-20,33]): Invalid response: -21 (type '?' for help)
Please enter an INTEGER value between -20 and 33 for test-option4: Invalid response: 34 (type '?' for help)
Please enter an INTEGER value between -20 and 33 for test-option4: This is a test option
Please enter an INTEGER value between -20 and 33 for test-option4: value = 5
Option test-option5 [0.5](Real): value = 0.3
Option test-option6(Real): value = 0.4
Option test-option7 [0.5](Real: [0.1,1]): Invalid response: 0.0 (type '?' for help)
Please enter a REAL value between 0.1 and 1 for test-option7 (Default is 0.5): Invalid response: 1.3 (type '?' for help)
Please enter a REAL value between 0.1 and 1 for test-option7 (Default is 0.5): value = 0.5
Option test-option8(Real: [-0.5,0.5]): value = 0
Option enum-option1 [t12](t10, t11, t12, t13): value = 2
Option enum-option2 [t21](t20, t21, t22, t23): value = 0
Option enum-option3 [t12](t10, t11, t12, t13): Invalid response: t21 (type '?' for help)
Please enter an enumerated value for enum-option3 (Default is t12).
Allowable values are: t10, t11, t12, t13
: 
Invalid response: t21 (type '?' for help)
Please enter an enumerated value for enum-option3 (Default is t12).
Allowable values are: t10, t11, t12, t13
: 
value = 3
Option enum-option4 [t22](t20, t21, t22, t23): WARNING: Default value "-0.5" for option bad-option1 is ILLEGAL!  Default ignored.
Option bad-option1(Real: [0,1]): Help
Please enter a REAL value between 0 and 1 for bad-option1: value = 0.5
Option should-prompt1(integer): Option should-prompt2 [10](integer): Option env-option1 [10](integer): value = 10
Option env-option2 [15](integer): value = 15
WARNING: Default value "abc" for option bad-enum1 is ILLEGAL!  Default ignored.
Option bad-enum1(t10, t11, t12, t13): value = 5
Option force-prompt2(integer): value = 5
Option bool-option1 [true](true, false, yes, no): Invalid response: 10 (type '?' for help)
Please enter an enumerated value for bool-option1 (Default is true).
Allowable values are: true, false, yes, no
: 
value = T
Option bool-option2(true, false, yes, no): value = T
Option enum-no-default(t10, t11, t12, t13): This is an enum option
Please enter an enumerated value for enum-no-default.
Allowable values are: t10, t11, t12, t13
: 
value = 3
