.TH MAGTOPPM 1 2008-11-29 "libmaglo 0.99" "libmaglo User's Manual"
.SH NAME
magtoppm \- convert MAG image to a PPM image
.SH SYNOPSIS
.B magtoppm
.I input
[
.I output
]
.SH DESCRIPTION
.I magtoppm
converts a file in the 
.SM MAG
format to
.SM PNM.
If no
.SM output
file is specified on the command line,
.I magtoppm
will write to the standard output.
.SH SEE ALSO
.I libmaglo(7)
