.TH MAGVERSION 3 2008-11-29 "libmaglo 0.99" "libmaglo Programmer's Manual"
.SH NAME
MAGversion \- returns version of libmaglo
.SH SYNOPSIS
.nf
.B #include <maglo.h>
.sp
.BI "int MAGversion(" void ");"
.fi
.SH DESCRIPTION
Returns interface version of the
.I "libmaglo" 
library.
.SH RETURN VALUES
For version 0.99, 
.BI "MAGversion"
returns value `99'.
.SH SEE ALSO
.I libmaglo(7)
