.r icitypes.1
.TH "icitypes" "1"
.SH NAME
icitypes \- ICI data types
.SH DESCRIPTION

.PP
Ici supports a base set of standard data types.  Each is identified by
a simple name.  In summary these are:

.TP 1i
.B array
An ordered sequence of other objects.
.TP 1i
.B file
An open file reference.
.TP 1i
.B float
A double precision floating point number.
.TP 1i
.B func
A function.
.TP 1i
.B int
A signed 32 bit integer.
.TP 1i
.B mem
References to raw machine memory.
.TP 1i
.B ptr
A reference to a storage location.
.TP 1i
.B regexp
A compiled regular expression.
.TP 1i
.B set
An unordered collection of other objects.
.TP 1i
.B string
An ordered sequence of 8 bit characters.
.TP 1i
.B struct
An unordered set of pairs of objects.
