Enter attribute.  End with -1
Attribute 0 is handicapped infants
Attribute 1 is water project cost sharing
Attribute 2 is adoption of the budget resolution
Attribute 3 is physician fee freeze
Attribute 4 is el salvador aid
Attribute 5 is religious groups in schools
Attribute 6 is anti satellite test ban
Attribute 7 is aid to nicaraguan contras
Attribute 8 is mx missile
Attribute 9 is immigration
Attribute 10 is synfuels corporation cutback
Attribute 11 is education spending
Attribute 12 is superfund right to sue
Attribute 13 is crime
Attribute 14 is duty free exports
Attribute 15 is export administration act south africa
