# https://travis-ci.org/dryproject/libc11
language: c
compiler:
  - clang
  - gcc
before_script:
  - ./autogen.sh
script:
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then ./configure && make && make check; fi
branches:
  only:
    - master
    - coverity

# https://scan.coverity.com/projects/3219
env:
  global:
  - secure: "RDJaKmhYWNqxy/ou+zuHcJIdOQ24UIy/9WH6A6sAxCQS9dkzKOdrJi68utDrmRb1uy2gy4om42XyJ+93dLAQuQvFBEI34x0fGyahBbHW6nZk/EWdpGYN3tDr5ZzOySdkfJkac+1By7mYrdvO9zFU7SQJQbxxgOiaeqF0JEH9z6I=" # COVERITY_SCAN_TOKEN
addons:
  coverity_scan:
    project:
      name: dryproject/libc11
    notification_email: arto@bendiken.net
    build_command_prepend: ./configure
    build_command: make
    branch_pattern: coverity
