# Configuration file for MLC++ make system
#
# definition that all makefiles may need
.SUFFIXES:
.SUFFIXES: .o .c

MAKE=pmake
SHELL=/bin/csh
AR=ar
# FAST_AR archives into a new archive
FAST_AR=ar cq
#CLCC=/usr/local/CenterLine/bin/clcc
#CLCC is for regular CC compiler.
CLCC=cc
#GNUCC is to be used to compile gnulib
GNUCC=CC -O2
RM=/usr/bin/rm
MKDIR=/usr/bin/mkdir
CHMOD=/usr/bin/chmod
TOUCH=/usr/bin/touch
GENTAGS=etags
# Set to /bin/true if no need to do ranlib; otherwise, set to ranlib
RANLIB=/bin/true
# TC report is for use with testcenter (can be anything if not used).
TCREPORT=/usr/local/CenterLine/bin/tcreport

MFLAGS=-k		# flags to pass to make in a directory
