#include <float.h>

FLT_OPT(	SM,		-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(	SD,		-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(	SI,		-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(	SX,		-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(	SY,		-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")

FLT_OPT(	ME,		-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(	DE,		-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(	IE,		-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(	XE,		-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(	YE,		-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")

FLT_OPT(	MD,		-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(	MI,		-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(	MX,		-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(	MY,		-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")

FLT_OPT(	DD,		-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(	II,		-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(	XX,		-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(	YY,		-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")

FLT_OPT(G,			-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(E,			-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(g,			-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(e,			-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(dg,			-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(de,			-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(tg,			-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(te,			-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(tdg,		-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(tde,		-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(Lg,			-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(Le,			-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(Ldg,		-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(Lde,		-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(Rg,			-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(Re,			-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(Rdg,		-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
FLT_OPT(Rde,		-,			FLT_MAX,		-FLT_MAX,		FLT_MAX,		"Trans score")
