all :
	make -C krnl
	make -C apps

install :
	make -C krnl install
	make -C apps install

clean :
	make -C krnl clean
	make -C apps clean
	make -C lib  clean

dep :
	make -C krnl dep
	make -C apps dep
	make -C lib  dep
