#!/bin/csh

cat << END_OF_HEAD
<HTML>
<HEAD>
<TITLE>Examples in $PWD</TITLE>
</HEAD>
<BODY>
<H1>Examples in $PWD</H1>
END_OF_HEAD

if (-e README) then
	echo "Here is the README file."
endif

foreach i (*.in)
	echo "<UL>" $i:r
	foreach j ($i:r.*)
		echo "<LI> $j"
	end
	echo "</UL>" $i:r
end

cat << END_OF_TAIL
<P>
<I>
These activities are projects of the
<A HREF="http://www.mcs.anl.gov/">Mathematics and Computer Science Division</A>
of
<A HREF="http://www.anl.gov/">Argonne National Laboratory</A>.
</I>
</BODY>
</HTML>
END_OF_TAIL



