t_InstList executing
Testing zero projection
zeroBag: 
Label0.
Label1.
Label2.
Label3.
Label3.
Label3.

zeroBag2: 
Label0.
Label1.
Label2.
Label3.
Label3.
Label3.

zeroBag3: 
No instances

Testing my copy!
Testing clone
Done with my copy and clone!
No instances
List before shuffle:
young, myope, no, reduced, no contact lenses.
young, myope, no, normal, soft contact lenses.
young, myope, yes, reduced, no contact lenses.
young, myope, yes, normal, hard contanct lenses.
young, hypermetrope, no, reduced, no contact lenses.
young, hypermetrope, no, normal, soft contact lenses.
young, hypermetrope, yes, reduced, no contact lenses.
young, hypermetrope, yes, normal, hard contanct lenses.
pre-presbyopic, myope, no, reduced, no contact lenses.
pre-presbyopic, myope, no, normal, soft contact lenses.
pre-presbyopic, myope, yes, reduced, no contact lenses.
pre-presbyopic, myope, yes, normal, hard contanct lenses.
pre-presbyopic, hypermetrope, no, reduced, no contact lenses.
pre-presbyopic, hypermetrope, no, normal, soft contact lenses.
pre-presbyopic, hypermetrope, yes, reduced, no contact lenses.
pre-presbyopic, hypermetrope, yes, normal, no contact lenses.
presbyopic, myope, no, reduced, no contact lenses.
presbyopic, myope, no, normal, no contact lenses.
presbyopic, myope, yes, reduced, no contact lenses.
presbyopic, myope, yes, normal, hard contanct lenses.
presbyopic, hypermetrope, no, reduced, no contact lenses.
presbyopic, hypermetrope, no, normal, soft contact lenses.
presbyopic, hypermetrope, yes, reduced, no contact lenses.
presbyopic, hypermetrope, yes, normal, no contact lenses.
List after shuffling
presbyopic, hypermetrope, no, normal, soft contact lenses.
young, myope, no, normal, soft contact lenses.
presbyopic, myope, no, reduced, no contact lenses.
pre-presbyopic, myope, no, reduced, no contact lenses.
young, myope, yes, normal, hard contanct lenses.
young, hypermetrope, no, normal, soft contact lenses.
pre-presbyopic, myope, yes, normal, hard contanct lenses.
presbyopic, myope, yes, reduced, no contact lenses.
young, myope, no, reduced, no contact lenses.
pre-presbyopic, hypermetrope, no, normal, soft contact lenses.
young, myope, yes, reduced, no contact lenses.
pre-presbyopic, hypermetrope, yes, normal, no contact lenses.
presbyopic, hypermetrope, yes, normal, no contact lenses.
presbyopic, hypermetrope, yes, reduced, no contact lenses.
young, hypermetrope, yes, normal, hard contanct lenses.
pre-presbyopic, hypermetrope, no, reduced, no contact lenses.
pre-presbyopic, hypermetrope, yes, reduced, no contact lenses.
presbyopic, myope, yes, normal, hard contanct lenses.
young, hypermetrope, no, reduced, no contact lenses.
presbyopic, hypermetrope, no, reduced, no contact lenses.
pre-presbyopic, myope, yes, reduced, no contact lenses.
presbyopic, myope, no, normal, no contact lenses.
pre-presbyopic, myope, no, normal, soft contact lenses.
young, hypermetrope, yes, reduced, no contact lenses.
Warning: no instances in file t_InstList.badeof
No instances
one, 1, -10, foo.
one, 0, 10, bar.
two, 2, 1000, foo.
two, 5, 100, bar.

Normalized values:
0.2	0
0	0.019802
0.4	1
1	0.108911
Normalizing MAXFLOAT and -MAXFLOAT
6.80565e+37	-6.80565e+37
No instances
Check corrupt unknown part 1 OK
Check corrupt unknown part 2 OK
Check corrupt had 465 instances, now  it has 265 (should be somewhat over a half)
