// MLC++ - Machine Learning Library in -*- C++ -*-
// See Descrip.txt for terms and conditions relating to use and distribution.

// This is a utility for MLC++
// It is not part of the MLC++ library itself, but instead uses the
//   library to provide a useful function.

/***************************************************************************
  Description  : Cross validate wrapper.
  Usage        : Environment variables to set:
                   INDUCER  (see env_inducer)
                   INDUCERNAME (optional)
                 Validation can be done in two ways:
		   * FILESTEM (optional, can generated by GenCValidate)
		   * DATAFILE (for in-memory validation).
                     If DATAFILE has a suffix, we use that suffix
		     for the datafile.  Very useful for (.all) files.
		     Otherwise, .data is used.
                   * TESTFILE (optional) Generate single run on DATAFILE,
		        test on TESTFILE.
		     CV_FOLDS (optional, 20)
		     CV_TIMES (optional, 1)
		     ACC_TRIM  (optional, 0.0)
		     CV_TYPE  (optional in {cv, cvinc, stratcv}
                               which are regular cv, incremental, stratified.
		               default is stratcv)
  Enhancements :
  History      : Ronny Kohavi                                       1/22/94
                   Initial revision
***************************************************************************/

#include <basics.h>
#include <env_inducer.h>
#include <CVIncremental.h>
#include <StratifiedCV.h>
#include <CtrInstList.h>
#include <CatTestResult.h>
#include <mlcIO.h>

RCSID("MLC++, $RCSfile: u_CV.c,v $ $Revision: 1.20 $")

main()
{
   BaseInducer *inducer; // don't env_inducer now because we want to update
		     // the globalLogLevel
   CrossValidator *cv;
   Real cvTrim = get_env_default("ACC_TRIM", "0").real_value();
   MString fileStem = get_env_default("FILESTEM", "");
   MString dataFile = get_env_default("DATAFILE", "");

   if (fileStem == "" && dataFile == "")
      err << "Either DATAFILE or FILESTEM must be non-null" << fatal_error;
   

   int seed         = (int)(get_env_default("SEED", "7258789").long_value());
   
   int cvFolds = get_env_default("CV_FOLDS",
		   MString(CrossValidator::defaultNumFolds, 0)).short_value();
   int cvTimes = get_env_default("CV_TIMES",
                   MString(CrossValidator::defaultNumTimes, 0)).short_value();

   CtrInstanceList* data = NULL;
   MString rootName;

   if (fileStem != "") {
      if (dataFile != "")
	 err << "Both FILESTEM and DATAFILE not NULL" << fatal_error;

      if (fileStem.contains("."))
	 err << "FILESTEM=" << fileStem << " must not contain period" <<
	    fatal_error;

      rootName = fileStem;
      GLOBLOG(1, "FILESTEM is " << fileStem << endl);
      // Don't show too much in Inducer
      int saveLogLevel = globalLogLevel;

      globalLogLevel = max(globalLogLevel-3, 0);
      inducer = env_inducer();

      cv = new CrossValidator(cvFolds, cvTimes);
      cv->set_log_level(saveLogLevel); //just for CV have higher level.
      cv->estimate_accuracy(*inducer, fileStem);
   } else {
      if (dataFile.contains("."))
	 rootName = MString(dataFile, dataFile.index("."));
      else {
	 rootName = dataFile;
	 dataFile += ".data";
      }

      data = new CtrInstanceList("", rootName + ".names", dataFile);
      GLOBLOG(1, "Folds:" << cvFolds << " times:" << cvTimes <<
               " seed:" << seed << endl);
      Mcout << "DATAFILE is " << dataFile << " with " <<
	      data->num_instances() << " instances" << endl;
      // Don't show too much in Inducer
      int saveLogLevel = globalLogLevel;
      globalLogLevel = max(globalLogLevel-3, 0);
      inducer = env_inducer();
      
      MString cvType(get_env_default("CV_TYPE", "cv"));
      
      if (cvType.equal_ignore_case("cvinc")) {
         GLOBLOG(1, "CV using incremental inducer" << inducer->description()
		 << endl);
	 cv = new CVIncremental(cvFolds, cvTimes);
      }
      else if (cvType.equal_ignore_case("cv")) {
	 cv = new CrossValidator(cvFolds, cvTimes);
         GLOBLOG(1, "CV Using inducer" << inducer->description() << endl);
      } else if (cvType.equal_ignore_case("stratcv")) {
	 cv = new StratifiedCV(cvFolds, cvTimes);
         GLOBLOG(1, "Stratified CV using inducer"
		 << inducer->description() << endl);
      } else
	 err << "Unrecognized CV_TYPE.  Must be: cv, cvinc, or stratcv"
	     << fatal_error;
	 
      cv->set_log_level(saveLogLevel); //just for CV have higher level.
      cv->init_rand_num_gen(seed);

      cv->estimate_accuracy(*inducer, *data);
   }

   Mcout << "Inducer: " << inducer->description() << ' ';
   if (cvTrim != 0)
      Mcout << ", Trim: " << cvTrim;
   Mcout << cv->get_acc_data() << endl;

   MString testFile = get_env_default("TESTFILE", "");
   if (testFile != "" && data != NULL) {
      if (!testFile.contains(".")) {
	 extern const MString defaultTestExt;
	 testFile += defaultTestExt;
      }
      Mcout << "Testing on " << testFile << endl;
      InstanceList testList("", rootName + ".names", testFile);
      Mcout << "Accuracy on test file: " << 
	 inducer->train_and_test(data, testList) << endl;
   }


   delete inducer;
   delete data;

   return 0; // return success to shell
}
