t_DecisionTree executing
Root: Root ConstCat-0

[0](Root ConstCat-0) : [0]--(edge-1)-->[1][0]--(edge0)-->[6][0]--(edge1)-->[11]
[1](ConstCat0-0-0) : [1]--(edge)-->[2]
[2](ConstCat0-0-1) : [2]--(edge)-->[3]
[3](ConstCat0-0-2) : [3]--(edge)-->[4]
[4](ConstCat0-0-3) : [4]--(edge)-->[5]
[5](ConstCat0-0-4) : 
[6](ConstCat0-1-0) : [6]--(edge)-->[7]
[7](ConstCat0-1-1) : [7]--(edge)-->[8]
[8](ConstCat0-1-2) : [8]--(edge)-->[9]
[9](ConstCat0-1-3) : [9]--(edge)-->[10]
[10](ConstCat0-1-4) : 
[11](ConstCat0-2-0) : [11]--(edge)-->[12]
[12](ConstCat0-2-1) : [12]--(edge)-->[13]
[13](ConstCat0-2-2) : [13]--(edge)-->[14]
[14](ConstCat0-2-3) : [14]--(edge)-->[15]
[15](ConstCat0-2-4) : 

