t_OneR executing
0, D1.
0, D1.
0, D1.
0, D1.
1, D1.
1, D1.
1, D3.
1, D3.
1, D3.
1, D3.
1, D3.
1, D3.
1, D3.
2, D4.
2, D4.
2, D4.
2, D4.
2, D4.
2, D4.
2, D4.
2, D4.
2, D4.
2, D4.
2, D4.
2, D4.
3, D2.
3, D2.
3, D2.
3, D2.
3, D2.
3, D2.

------------Original Schema ----------------
Attributes:
Attribute 21: continuous.
Label: Label: D1, D2, D3, D4.
-------------- New Schema ------------------
Attributes:
Attribute 21: -Inf-0\.5, 0\.5-1\.5, 1\.5-2\.5, 2\.5-Inf.
Label: Label: D1, D2, D3, D4.
-----------Real Discretizors----------------

Discretization of Attribute: "Attribute 21"

Bin0: (-INF, 0.5)
Bin1: [0.5,1.5)
Bin2: [1.5,2.5)
Bin3: [2.5,+INF)
 ----------Discretized bag -----------------
-Inf-0\.5, D1.
-Inf-0\.5, D1.
-Inf-0\.5, D1.
-Inf-0\.5, D1.
0\.5-1\.5, D1.
0\.5-1\.5, D1.
0\.5-1\.5, D3.
0\.5-1\.5, D3.
0\.5-1\.5, D3.
0\.5-1\.5, D3.
0\.5-1\.5, D3.
0\.5-1\.5, D3.
0\.5-1\.5, D3.
1\.5-2\.5, D4.
1\.5-2\.5, D4.
1\.5-2\.5, D4.
1\.5-2\.5, D4.
1\.5-2\.5, D4.
1\.5-2\.5, D4.
1\.5-2\.5, D4.
1\.5-2\.5, D4.
1\.5-2\.5, D4.
1\.5-2\.5, D4.
1\.5-2\.5, D4.
1\.5-2\.5, D4.
2\.5-Inf, D2.
2\.5-Inf, D2.
2\.5-Inf, D2.
2\.5-Inf, D2.
2\.5-Inf, D2.
2\.5-Inf, D2.
t_OneR successful
